services:
  backend:
    build: ./backend/
    ports:
      - "8080:5000"
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build: ./frontend/
    ports:
      - "8000:5000"
  database:
    image: "postgres"
    environment:
      POSTGRES_DB: screeners_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d screeners_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s