"""add question to screener table

Revision ID: 34a985c4db6c
Revises: 695370dd866b
Create Date: 2025-03-25 21:53:03.524160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a985c4db6c'
down_revision = '695370dd866b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_to_question',
    sa.Column('section_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['screener_section.id'], ),
    sa.PrimaryKeyConstraint('section_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_to_question')
    # ### end Alembic commands ###
